export enum GrpcClientType {
  ORCA_WHIRLPOOL = 'ORCA_WHIRLPOOL',
  RAYDIUM_POOL = 'RAYDIUM_POOL',
  BLOCK_META = 'BLOCK_META',
  JUPITER_TRANSACTION = 'JUPITER_TRANSACTION',
  SLOT = 'SLOT',
}

export enum GrpcSubscriptionStatus {
  CONNECTING = 'CONNECTING',
  SUBSCRIBED = 'SUBSCRIBED',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
} 